"use client";
import { useLayoutEffect, useState, type PointerEvent } from "react";
type Rect={left:number;top:number;width:number;height:number};
type Props={sectionId:string;elementKey:string;widthPercent?:number;offsetX?:number;offsetY?:number;onCommit:(widthPercent:number)=>void;onMoveCommit:(offsetX:number,offsetY:number)=>void};
export default function ImageResizeOverlay({sectionId,elementKey,widthPercent,offsetX=0,offsetY=0,onCommit,onMoveCommit}:Props){
 const[rect,setRect]=useState<Rect>();const[displayPercent,setDisplayPercent]=useState(widthPercent??50);
 const selector=`[data-section-id="${CSS.escape(sectionId)}"] [data-editor-element="${CSS.escape(elementKey)}"]`;
 const locate=()=>{const element=document.querySelector<HTMLElement>(selector);if(!element)return setRect(undefined);const box=element.getBoundingClientRect();setRect({left:box.left,top:box.top,width:box.width,height:box.height});if(widthPercent)setDisplayPercent(widthPercent)};
 useLayoutEffect(()=>{locate();window.addEventListener("resize",locate);window.addEventListener("scroll",locate,true);return()=>{window.removeEventListener("resize",locate);window.removeEventListener("scroll",locate,true)}},[sectionId,elementKey,widthPercent]);
 const start=(event:PointerEvent<HTMLButtonElement>,direction:-1|1)=>{event.preventDefault();event.stopPropagation();const handle=event.currentTarget;handle.setPointerCapture(event.pointerId);const section=document.querySelector<HTMLElement>(`[data-section-id="${CSS.escape(sectionId)}"]`);const element=document.querySelector<HTMLElement>(selector);if(!section||!element)return;const startX=event.clientX;const sectionWidth=section.getBoundingClientRect().width;const startWidth=element.getBoundingClientRect().width;const usesGridTrack=elementKey==="imageUrl"&&(section.dataset.sectionType==="hero"||section.dataset.sectionType==="about");let next=Math.max(10,Math.min(100,startWidth/sectionWidth*100));const move=(moveEvent:globalThis.PointerEvent)=>{const pixels=Math.max(sectionWidth*.1,Math.min(sectionWidth,startWidth+(moveEvent.clientX-startX)*direction));next=Math.round(pixels/sectionWidth*1000)/10;if(usesGridTrack){section.dataset.imageResized="true";section.style.setProperty("--section-image-width",`${next}%`)}else{element.style.width=`${next}%`;element.style.maxWidth="100%"}setDisplayPercent(next);locate()};const finish=()=>{handle.removeEventListener("pointermove",move);handle.removeEventListener("pointerup",finish);handle.removeEventListener("pointercancel",finish);onCommit(next)};handle.addEventListener("pointermove",move);handle.addEventListener("pointerup",finish);handle.addEventListener("pointercancel",finish)};
 const startMove=(event:PointerEvent<HTMLButtonElement>)=>{event.preventDefault();event.stopPropagation();const handle=event.currentTarget;handle.setPointerCapture(event.pointerId);const element=document.querySelector<HTMLElement>(selector);if(!element)return;const startX=event.clientX,startY=event.clientY;let nextX=offsetX,nextY=offsetY;const move=(moveEvent:globalThis.PointerEvent)=>{nextX=Math.round(offsetX+moveEvent.clientX-startX);nextY=Math.round(offsetY+moveEvent.clientY-startY);element.style.position="relative";element.style.left=`${nextX}px`;element.style.top=`${nextY}px`;locate()};const finish=()=>{handle.removeEventListener("pointermove",move);handle.removeEventListener("pointerup",finish);handle.removeEventListener("pointercancel",finish);onMoveCommit(nextX,nextY)};handle.addEventListener("pointermove",move);handle.addEventListener("pointerup",finish);handle.addEventListener("pointercancel",finish)};
 if(!rect)return null;return <div className="image-resize-overlay" style={rect} aria-label="Resize and move selected element"><button type="button" className="image-resize-handle left" aria-label="Resize from left" onPointerDown={event=>start(event,-1)}/><button type="button" className="element-move-handle" aria-label="Move element" title="Drag to move" onPointerDown={startMove}>✥</button><button type="button" className="image-resize-handle right" aria-label="Resize from right" onPointerDown={event=>start(event,1)}/><span>{Math.round(displayPercent)}%</span></div>
}
