import type { CSSProperties, MouseEvent } from "react";
import type { EditableElementKey, WebsiteSectionComponentProps } from "@/types/website";
import { getAlignmentClasses } from "@/utils/alignment";
export default function HeroLuxury({section,theme,editable=false,selectedElementKey,onSelectElement,elementStyles,onRequestImagePicker}:WebsiteSectionComponentProps){
 const alignment=getAlignmentClasses(section.props.alignment);const cls=(key:EditableElementKey)=>editable?`cursor-pointer rounded-sm outline outline-2 outline-offset-4 ${selectedElementKey===key?"outline-blue-500":"outline-transparent hover:outline-blue-300"}`:"";
 const select=(key:EditableElementKey)=>(event:MouseEvent<HTMLElement>)=>{if(!editable)return;event.stopPropagation();onSelectElement?.(key)};
 const style=(key:EditableElementKey):CSSProperties=>{const {buttonStyle:_,widthPercent,...rest}=elementStyles?.[key]??{};return{...rest,...(widthPercent?{width:"100%"}:{})}};
 const buttonStyle=(key:"buttonText"|"secondaryButtonText"):CSSProperties=>{const base=style(key);const filled=(elementStyles?.[key]?.buttonStyle??(key==="buttonText"?"filled":"outline"))==="filled";return {...base,backgroundColor:filled?"#18181b":"transparent",borderColor:filled?"#18181b":"#d4d4d8",color:base.color??(filled?"#fff":"#3f3f46")}};
 return <section className="grid min-h-[520px] overflow-hidden rounded-[30px] bg-[#fdf8f2] text-zinc-900" style={{backgroundColor:theme.backgroundColor,color:theme.textColor}}><div className="grid gap-10 p-8 lg:grid-cols-[1.15fr_.85fr] lg:p-12"><div className={`flex flex-col justify-center ${alignment.container}`}><p onDoubleClick={select("statLabel")} data-editor-element="statLabel" className={`mb-4 text-sm font-medium uppercase tracking-[.3em] text-blue-600 ${cls("statLabel")}`} style={style("statLabel")}>{section.props.statLabel}</p><h1 onDoubleClick={select("title")} data-editor-element="title" className={`max-w-2xl text-5xl font-black leading-[.95] sm:text-6xl ${cls("title")}`} style={{fontFamily:theme.fontFamily,...style("title")}}>{section.props.title}</h1><p onDoubleClick={select("subtitle")} data-editor-element="subtitle" className={`mt-6 max-w-xl text-lg text-zinc-600 ${cls("subtitle")}`} style={style("subtitle")}>{section.props.subtitle}</p><div className={`mt-8 flex flex-wrap gap-3 ${alignment.actions}`}><button type="button" onClick={select("buttonText")} data-editor-element="buttonText" className={`rounded-full border px-6 py-3 font-medium ${cls("buttonText")}`} style={buttonStyle("buttonText")}>{section.props.buttonText}</button><button type="button" onClick={select("secondaryButtonText")} data-editor-element="secondaryButtonText" className={`rounded-full border px-6 py-3 font-medium ${cls("secondaryButtonText")}`} style={buttonStyle("secondaryButtonText")}>{section.props.secondaryButtonText}</button></div><div className="mt-10 flex gap-8"><div><strong className="text-2xl">{section.props.statValue}</strong><p className="text-xs text-zinc-500">Teams launched</p></div><div><strong className="text-2xl">4.9/5</strong><p className="text-xs text-zinc-500">Partner rating</p></div></div></div><div className="relative flex items-end"><div className="absolute -left-5 top-8 z-10 rounded-2xl bg-white p-4 shadow-xl"><strong>+38%</strong><p className="text-xs text-zinc-500">Faster launches</p></div><img onClick={select("imageUrl")} onDoubleClick={event=>{if(!editable)return;event.stopPropagation();onSelectElement?.("imageUrl");onRequestImagePicker?.()}} data-editor-element="imageUrl" src={section.props.imageUrl} alt={section.props.altText??section.props.title} className={`h-full min-h-[360px] w-full rounded-[24px] object-cover shadow-2xl ${cls("imageUrl")}`} style={style("imageUrl")}/></div></div></section>;
}
