import { designPresets } from "@/presets";
import type { WebsiteJSON, WebsiteTheme } from "@/types/website";
import ThemeColorControl from "./ThemeColorControl";
import ThemeTypographyControl from "./ThemeTypographyControl";
import ThemeSpacingControl from "./ThemeSpacingControl";
import ThemeImageTreatmentControl from "./ThemeImageTreatmentControl";
import ThemePalettePresets from "./ThemePalettePresets";
import type { SetWebsiteOptions } from "@/hooks/useWebsiteHistory";
type ColorKey="backgroundColor"|"surfaceColor"|"primaryColor"|"secondaryColor"|"accentColor"|"textColor"|"mutedTextColor";
const colors:Array<[string,ColorKey]>=[["Background","backgroundColor"],["Surface","surfaceColor"],["Primary","primaryColor"],["Secondary","secondaryColor"],["Accent","accentColor"],["Text","textColor"],["Muted text","mutedTextColor"]];
export default function ThemePanel({website,onChange,onChooseBackground}:{website:WebsiteJSON;onChange:(website:WebsiteJSON,options:SetWebsiteOptions)=>void;onChooseBackground?:()=>void}){
 const base=website.presetId?designPresets[website.presetId].theme:website.theme;
 const update=(patch:Partial<WebsiteTheme>)=>{const fields=Object.keys(patch).sort();onChange({...website,isThemeCustomized:true,theme:{...website.theme,...patch}},{label:fields.length===1?`Change theme ${fields[0]}`:"Apply theme palette",group:fields.length===1?`theme:${fields[0]}`:undefined})};
 return <div className="editor-panel"><h2>Theme</h2><p>Changes colors, fonts, radius, spacing, density, backgrounds, and image treatment without replacing the website layout.</p><p className="mt-2 text-xs uppercase">{website.presetId?designPresets[website.presetId].name:"Custom theme"}{website.isThemeCustomized?" · Customized":""}</p><h3>Palette presets</h3><ThemePalettePresets onApply={update}/><h3>Colors</h3><div className="space-y-2">{colors.map(([label,key])=><ThemeColorControl key={key} label={label} value={website.theme[key]} defaultValue={base[key]} onChange={value=>update({[key]:value})}/>)}</div><h3>Typography</h3><ThemeTypographyControl theme={website.theme} onChange={update}/><h3>Layout</h3><ThemeSpacingControl theme={website.theme} onChange={update}/><h3>Page background</h3><div className="space-y-2"><input className="w-full rounded border p-2 text-xs" value={website.theme.backgroundImageUrl??""} placeholder="Background image URL" onChange={event=>update({backgroundImageUrl:event.target.value})}/><div className="flex gap-2"><button type="button" onClick={onChooseBackground}>Choose from assets</button>{website.theme.backgroundImageUrl&&<button type="button" onClick={()=>update({backgroundImageUrl:""})}>Remove</button>}</div><select value={website.theme.backgroundImageFit??"cover"} onChange={event=>update({backgroundImageFit:event.target.value as "cover"|"contain"})}><option value="cover">Cover page</option><option value="contain">Contain image</option></select></div><h3>Images</h3><ThemeImageTreatmentControl value={website.theme.imageTreatment} onChange={imageTreatment=>update({imageTreatment})}/></div>;
}
