import SectionRenderer from "@/renderer/SectionRenderer";
import FloatingElementToolbar from "@/components/editor/FloatingElementToolbar";
import type { EditableElementKey, EditableElementStyle, EditorSelection, SectionVariant, WebsiteJSON, WebsiteSection, WebsiteSectionProps } from "@/types/website";
type Props={website:WebsiteJSON;selection?:EditorSelection;onSelectionChange?:(s:EditorSelection)=>void;onUpdateElement?:(id:string,key:EditableElementKey,value:string)=>void;onUpdateElementStyle?:(id:string,key:EditableElementKey,p:Partial<EditableElementStyle>)=>void;onUpdateElementLink?:(id:string,key:EditableElementKey,v:string)=>void;onRemoveSection?:(id:string)=>void;onDuplicateSection?:(id:string)=>void;onChangeVariant?:(id:string,v:SectionVariant)=>void;onMoveSection?:(from:string,to:string)=>void;editable?:boolean};
const valueOf=(section:WebsiteSection,key:EditableElementKey)=>key.startsWith("content.")?section.content?.[key]??"":String(section.props[key as keyof WebsiteSectionProps]??"");
export default function WebsiteRenderer(p:Props){const selected=p.website.sections.find(s=>s.id===p.selection?.sectionId);const key=p.selection?.elementKey;return <div className="rounded-[28px] border p-4 sm:p-6" style={{backgroundColor:p.website.theme.backgroundColor,color:p.website.theme.textColor}}><div className="space-y-4">{p.website.sections.map(section=><div key={section.id} data-section-id={section.id} onDragOver={e=>p.editable&&e.preventDefault()} onDrop={e=>{e.preventDefault();p.onMoveSection?.(e.dataTransfer.getData("text/section-id"),section.id)}} onClick={()=>p.editable&&p.onSelectionChange?.({sectionId:section.id})} className={`preview-section relative mb-6 border p-6 ${p.editable?"cursor-pointer":""} ${p.editable&&p.selection?.sectionId===section.id&&!key?"border-blue-500 ring-2":"border-transparent"}`}>
{p.editable&&p.selection?.sectionId===section.id&&<div className="section-floating-controls" onClick={e=>e.stopPropagation()}><span className="section-drag-handle" draggable onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData("text/section-id",section.id)}}>⋮⋮</span><button onClick={()=>p.onDuplicateSection?.(section.id)}>Duplicate</button><button onClick={()=>p.onChangeVariant?.(section.id,section.variant==="luxury"?"brutalist":"luxury")}>{section.variant}</button><button onClick={()=>p.onRemoveSection?.(section.id)}>Remove</button></div>}
<SectionRenderer section={section} theme={p.website.theme} editable={p.editable} selectedElementKey={p.selection?.sectionId===section.id?key:undefined} onSelectElement={elementKey=>p.onSelectionChange?.({sectionId:section.id,elementKey})} elementStyles={section.elementStyles} elementLinks={section.elementLinks} onUpdateElement={(elementKey,value)=>p.onUpdateElement?.(section.id,elementKey,value)}/></div>)}</div>
{p.editable&&key&&selected&&<FloatingElementToolbar sectionId={selected.id} elementKey={key} style={selected.elementStyles?.[key]??{}} link={selected.elementLinks?.[key]??""} value={valueOf(selected,key)} onValueChange={v=>p.onUpdateElement?.(selected.id,key,v)} onStyleChange={patch=>p.onUpdateElementStyle?.(selected.id,key,patch)} onLinkChange={v=>p.onUpdateElementLink?.(selected.id,key,v)}/>}</div>}
