import { useEffect, useRef, useState, type CSSProperties } from "react";
import SectionRenderer from "@/renderer/SectionRenderer";
import FloatingElementToolbar from "@/components/editor/FloatingElementToolbar";
import ImageResizeOverlay from "@/components/editor/ImageResizeOverlay";
import SectionHeightHandle from "@/components/editor/SectionHeightHandle";
import type { EditableElementKey, EditableElementStyle, EditorSelection, SectionVariant, WebsiteJSON, WebsiteSection, WebsiteSectionProps } from "@/types/website";

export type RenderMode = "preview" | "edit";
type Props = { website:WebsiteJSON; renderMode?:RenderMode; selectedSectionId?:string; selectedElement?:EditorSelection|null; onSelectSection?:(id:string)=>void; onSelectElement?:(selection:EditorSelection|null)=>void; selection?:EditorSelection; onSelectionChange?:(s:EditorSelection)=>void; onUpdateElement?:(id:string,key:EditableElementKey,value:string)=>void; onDeleteElement?:(id:string,key:EditableElementKey)=>void; onUpdateElementStyle?:(id:string,key:EditableElementKey,p:Partial<EditableElementStyle>)=>void; onUpdateElementLink?:(id:string,key:EditableElementKey,v:string)=>void; onUpdateSectionHeight?:(id:string,heightVh:number)=>void; onRemoveSection?:(id:string)=>void; onDuplicateSection?:(id:string)=>void; onChangeVariant?:(id:string,v:SectionVariant)=>void; onMoveSection?:(from:string,to:string)=>void; onRequestImagePicker?:(sectionId:string)=>void; editable?:boolean };
const formFieldKey = (key:EditableElementKey) => key.match(/^content\.formField\.(.+)\.(label|placeholder)$/);
const valueOf = (section:WebsiteSection,key:EditableElementKey) => {const match=formFieldKey(key);if(match){const field=section.props.formFields?.find(item=>item.id===match[1]);return field?.[match[2] as "label"|"placeholder"]??""}return key.startsWith("content.") ? section.content?.[key] ?? "" : String(section.props[key as keyof WebsiteSectionProps] ?? "")};

export default function WebsiteRenderer(p:Props) {
  const [menuSectionId,setMenuSectionId] = useState<string|null>(null);
  const menuRef = useRef<HTMLDivElement|null>(null);
  useEffect(()=>{const close=(event:PointerEvent)=>{if(!menuRef.current?.contains(event.target as Node))setMenuSectionId(null)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);
  const edit = p.renderMode ? p.renderMode === "edit" : Boolean(p.editable);
  const selection = p.selectedElement ?? p.selection;
  const select = (s:EditorSelection) => { p.onSelectionChange?.(s); p.onSelectElement?.(s); if(!s.elementKey)p.onSelectSection?.(s.sectionId) };
  const selected = p.website.sections.find(s=>s.id===selection?.sectionId);
  const key = selection?.elementKey;
  const deleteSelected=()=>{if(!selected||!key)return;if(p.onDeleteElement)p.onDeleteElement(selected.id,key);else p.onUpdateElement?.(selected.id,key,"");select({sectionId:selected.id})};
  const t = p.website.theme;
  const vars = {"--site-background":t.backgroundColor,"--site-surface":t.surfaceColor,"--site-primary":t.primaryColor,"--site-secondary":t.secondaryColor,"--site-accent":t.accentColor,"--site-text":t.textColor,"--site-muted":t.mutedTextColor,"--site-radius":`${t.borderRadius}px`,"--site-heading-font":t.headingFont,"--site-body-font":t.bodyFont} as CSSProperties;
  const backgroundStyle:CSSProperties = t.backgroundImageUrl ? {backgroundImage:`linear-gradient(${t.backgroundColor}cc,${t.backgroundColor}cc), url("${t.backgroundImageUrl}")`,backgroundSize:t.backgroundImageFit??"cover",backgroundPosition:"center",backgroundAttachment:"fixed"} : {};
  useEffect(()=>{document.querySelectorAll<HTMLElement>("[data-section-id]").forEach(element=>{element.id=element.dataset.sectionId??""})},[p.website.sections]);
  useEffect(()=>{if(!edit)return;const remove=(event:KeyboardEvent)=>{if(event.key!=="Delete"&&event.key!=="Backspace")return;const target=event.target as HTMLElement|null;if(target?.closest("input,textarea,select,[contenteditable='true']")||!key)return;event.preventDefault();deleteSelected()};window.addEventListener("keydown",remove);return()=>window.removeEventListener("keydown",remove)},[edit,key,selected]);
  return <main className={`site-renderer site-spacing-${t.spacingScale} site-density-${t.visualDensity} ${edit?"site-edit":"site-preview"}`} style={{...vars,...backgroundStyle}}>
    {p.website.sections.map(section=>{const imageWidth=section.elementStyles?.imageUrl?.widthPercent;const sectionStyle={...(imageWidth?{"--section-image-width":`${imageWidth}%`}:{}),...(section.backgroundColor?{"--section-background":section.backgroundColor,backgroundColor:section.backgroundColor}:{}),...(section.backgroundImageUrl?{backgroundImage:`linear-gradient(${section.backgroundColor??"transparent"}66,${section.backgroundColor??"transparent"}66), url("${section.backgroundImageUrl}")`,backgroundSize:section.backgroundImageFit??"cover",backgroundPosition:"center"}:{})} as CSSProperties;return <div key={section.id} data-section-id={section.id} data-section-type={section.type} data-image-resized={imageWidth?"true":undefined} style={sectionStyle} onDragOver={e=>edit&&e.preventDefault()} onDrop={e=>{if(!edit)return;e.preventDefault();p.onMoveSection?.(e.dataTransfer.getData("text/section-id"),section.id)}} onClick={event=>{if(edit){select({sectionId:section.id});return}const target=(event.target as HTMLElement).closest<HTMLElement>("[data-editor-element]");const elementKey=target?.dataset.editorElement as EditableElementKey|undefined;const link=elementKey?section.elementLinks?.[elementKey]:undefined;if(!link)return;event.preventDefault();if(link.startsWith("#")){document.querySelector(link)?.scrollIntoView({behavior:"smooth"})}else if(/^https?:\/\//i.test(link)){window.open(link,"_blank","noopener,noreferrer")}else{window.location.assign(link)}}} className={`site-section relative ${edit?"cursor-pointer":""} ${edit&&selection?.sectionId===section.id&&!key?"site-section-selected":""}`}>
      {edit&&selection?.sectionId===section.id&&<div className="section-floating-controls" onClick={e=>e.stopPropagation()}><span className="section-drag-handle" draggable title="Drag to reorder" onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData("text/section-id",section.id)}}>⠿</span><button className="section-variant-button" onClick={()=>p.onChangeVariant?.(section.id,section.variant==="luxury"?"brutalist":"luxury")}><span className="section-control-dot"/>{section.variant}</button><div className="section-more-wrap" ref={menuSectionId===section.id?menuRef:undefined}><button className="section-more-button" aria-label="Section actions" aria-expanded={menuSectionId===section.id} onClick={()=>setMenuSectionId(current=>current===section.id?null:section.id)}>•••</button>{menuSectionId===section.id&&<div className="section-action-menu"><button onClick={()=>{p.onDuplicateSection?.(section.id);setMenuSectionId(null)}}><span>⧉</span><span><b>Duplicate</b><small>Create a copy below</small></span></button><div className="section-menu-divider"/><button className="danger" onClick={()=>{p.onRemoveSection?.(section.id);setMenuSectionId(null)}}><span>⌫</span><span><b>Remove</b><small>Delete this section</small></span></button></div>}</div></div>}
      <SectionRenderer section={section} theme={t} editable={edit} selectedElementKey={selection?.sectionId===section.id?key:undefined} onSelectElement={elementKey=>select({sectionId:section.id,elementKey})} elementStyles={section.elementStyles} elementLinks={section.elementLinks} onUpdateElement={(elementKey,value)=>p.onUpdateElement?.(section.id,elementKey,value)} onRequestImagePicker={()=>p.onRequestImagePicker?.(section.id)}/>
      {edit&&section.type!=="navbar"&&<SectionHeightHandle sectionId={section.id} heightVh={section.heightVh??100} onCommit={heightVh=>p.onUpdateSectionHeight?.(section.id,heightVh)}/>}
    </div>})}
    {edit&&key&&selected&&<FloatingElementToolbar sectionId={selected.id} elementKey={key} style={selected.elementStyles?.[key]??{}} link={selected.elementLinks?.[key]??""} value={valueOf(selected,key)} onValueChange={v=>p.onUpdateElement?.(selected.id,key,v)} onDelete={deleteSelected} onStyleChange={patch=>p.onUpdateElementStyle?.(selected.id,key,patch)} onLinkChange={v=>p.onUpdateElementLink?.(selected.id,key,v)}/>}
    {edit&&key&&selected&&<ImageResizeOverlay sectionId={selected.id} elementKey={key} widthPercent={selected.elementStyles?.[key]?.widthPercent} heightPx={selected.elementStyles?.[key]?.heightPx} offsetX={selected.elementStyles?.[key]?.offsetX} offsetY={selected.elementStyles?.[key]?.offsetY} offsetXPercent={selected.elementStyles?.[key]?.offsetXPercent} offsetYPercent={selected.elementStyles?.[key]?.offsetYPercent} onCommit={(widthPercent,heightPx)=>p.onUpdateElementStyle?.(selected.id,key,{...(widthPercent!==undefined?{widthPercent}:{}),...(heightPx!==undefined?{heightPx}:{})})} onMoveCommit={(offsetX,offsetY,hiddenInPreview)=>p.onUpdateElementStyle?.(selected.id,key,{offsetX,offsetY,offsetXPercent:undefined,offsetYPercent:undefined,hiddenInPreview})}/>}
  </main>;
}
