import { useEffect, useRef, useState, type CSSProperties } from "react";
import SectionRenderer from "@/renderer/SectionRenderer";
import FloatingElementToolbar from "@/components/editor/FloatingElementToolbar";
import ImageResizeOverlay from "@/components/editor/ImageResizeOverlay";
import type { EditableElementKey, EditableElementStyle, EditorSelection, SectionVariant, WebsiteJSON, WebsiteSection, WebsiteSectionProps } from "@/types/website";

export type RenderMode = "preview" | "edit";
type Props = { website:WebsiteJSON; renderMode?:RenderMode; selectedSectionId?:string; selectedElement?:EditorSelection|null; onSelectSection?:(id:string)=>void; onSelectElement?:(selection:EditorSelection|null)=>void; selection?:EditorSelection; onSelectionChange?:(s:EditorSelection)=>void; onUpdateElement?:(id:string,key:EditableElementKey,value:string)=>void; onUpdateElementStyle?:(id:string,key:EditableElementKey,p:Partial<EditableElementStyle>)=>void; onUpdateElementLink?:(id:string,key:EditableElementKey,v:string)=>void; onRemoveSection?:(id:string)=>void; onDuplicateSection?:(id:string)=>void; onChangeVariant?:(id:string,v:SectionVariant)=>void; onMoveSection?:(from:string,to:string)=>void; onRequestImagePicker?:(sectionId:string)=>void; editable?:boolean };
const valueOf = (section:WebsiteSection,key:EditableElementKey) => key.startsWith("content.") ? section.content?.[key] ?? "" : String(section.props[key as keyof WebsiteSectionProps] ?? "");

export default function WebsiteRenderer(p:Props) {
  const [menuSectionId,setMenuSectionId] = useState<string|null>(null);
  const menuRef = useRef<HTMLDivElement|null>(null);
  useEffect(()=>{const close=(event:PointerEvent)=>{if(!menuRef.current?.contains(event.target as Node))setMenuSectionId(null)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);
  const edit = p.renderMode ? p.renderMode === "edit" : Boolean(p.editable);
  const selection = p.selectedElement ?? p.selection;
  const select = (s:EditorSelection) => { p.onSelectionChange?.(s); p.onSelectElement?.(s); if(!s.elementKey)p.onSelectSection?.(s.sectionId) };
  const selected = p.website.sections.find(s=>s.id===selection?.sectionId);
  const key = selection?.elementKey;
  const t = p.website.theme;
  const vars = {"--site-background":t.backgroundColor,"--site-surface":t.surfaceColor,"--site-primary":t.primaryColor,"--site-secondary":t.secondaryColor,"--site-accent":t.accentColor,"--site-text":t.textColor,"--site-muted":t.mutedTextColor,"--site-radius":`${t.borderRadius}px`,"--site-heading-font":t.headingFont,"--site-body-font":t.bodyFont} as CSSProperties;
  const backgroundStyle:CSSProperties = t.backgroundImageUrl ? {backgroundImage:`linear-gradient(${t.backgroundColor}cc,${t.backgroundColor}cc), url("${t.backgroundImageUrl}")`,backgroundSize:t.backgroundImageFit??"cover",backgroundPosition:"center",backgroundAttachment:"fixed"} : {};
  return <main className={`site-renderer site-spacing-${t.spacingScale} site-density-${t.visualDensity} ${edit?"site-edit":"site-preview"}`} style={{...vars,...backgroundStyle}}>
    {p.website.sections.map(section=>{const imageWidth=section.elementStyles?.imageUrl?.widthPercent;const sectionStyle={...(imageWidth?{"--section-image-width":`${imageWidth}%`}:{}),...(section.backgroundColor?{"--section-background":section.backgroundColor,backgroundColor:section.backgroundColor}:{})} as CSSProperties;return <div key={section.id} data-section-id={section.id} data-section-type={section.type} data-image-resized={imageWidth?"true":undefined} style={sectionStyle} onDragOver={e=>edit&&e.preventDefault()} onDrop={e=>{if(!edit)return;e.preventDefault();p.onMoveSection?.(e.dataTransfer.getData("text/section-id"),section.id)}} onClick={()=>edit&&select({sectionId:section.id})} className={`site-section relative ${edit?"cursor-pointer":""} ${edit&&selection?.sectionId===section.id&&!key?"site-section-selected":""}`}>
      {edit&&selection?.sectionId===section.id&&<div className="section-floating-controls" onClick={e=>e.stopPropagation()}><span className="section-drag-handle" draggable title="Drag to reorder" onDragStart={e=>{e.stopPropagation();e.dataTransfer.setData("text/section-id",section.id)}}>⠿</span><button className="section-variant-button" onClick={()=>p.onChangeVariant?.(section.id,section.variant==="luxury"?"brutalist":"luxury")}><span className="section-control-dot"/>{section.variant}</button><div className="section-more-wrap" ref={menuSectionId===section.id?menuRef:undefined}><button className="section-more-button" aria-label="Section actions" aria-expanded={menuSectionId===section.id} onClick={()=>setMenuSectionId(current=>current===section.id?null:section.id)}>•••</button>{menuSectionId===section.id&&<div className="section-action-menu"><button onClick={()=>{p.onDuplicateSection?.(section.id);setMenuSectionId(null)}}><span>⧉</span><span><b>Duplicate</b><small>Create a copy below</small></span></button><div className="section-menu-divider"/><button className="danger" onClick={()=>{p.onRemoveSection?.(section.id);setMenuSectionId(null)}}><span>⌫</span><span><b>Remove</b><small>Delete this section</small></span></button></div>}</div></div>}
      <SectionRenderer section={section} theme={t} editable={edit} selectedElementKey={selection?.sectionId===section.id?key:undefined} onSelectElement={elementKey=>select({sectionId:section.id,elementKey})} elementStyles={section.elementStyles} elementLinks={section.elementLinks} onUpdateElement={(elementKey,value)=>p.onUpdateElement?.(section.id,elementKey,value)} onRequestImagePicker={()=>p.onRequestImagePicker?.(section.id)}/>
    </div>})}
    {edit&&key&&selected&&<FloatingElementToolbar sectionId={selected.id} elementKey={key} style={selected.elementStyles?.[key]??{}} link={selected.elementLinks?.[key]??""} value={valueOf(selected,key)} onValueChange={v=>p.onUpdateElement?.(selected.id,key,v)} onStyleChange={patch=>p.onUpdateElementStyle?.(selected.id,key,patch)} onLinkChange={v=>p.onUpdateElementLink?.(selected.id,key,v)}/>}
    {edit&&key&&selected&&<ImageResizeOverlay sectionId={selected.id} elementKey={key} widthPercent={selected.elementStyles?.[key]?.widthPercent} offsetX={selected.elementStyles?.[key]?.offsetX} offsetY={selected.elementStyles?.[key]?.offsetY} onCommit={widthPercent=>p.onUpdateElementStyle?.(selected.id,key,{widthPercent})} onMoveCommit={(offsetX,offsetY)=>p.onUpdateElementStyle?.(selected.id,key,{offsetX,offsetY})}/>}
  </main>;
}
