"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { readApiResponse, ApiResponseError } from "@/lib/api-response";
import { SLUG_MAX_LENGTH, SLUG_MIN_LENGTH, slugSchema } from "@/features/publishing/slug";
import styles from "./publish.module.css";

type Details = { project: { id:string;name:string;slug:string|null;isPublished:boolean;updatedAt:string;publishedAt:string|null;draftRevision:number;publishedRevision:number|null }; preflight:{draftValid:boolean;unresolvedAssetCount:number} };
type Availability = "not-checked"|"checking"|"available"|"used"|"invalid"|"unable";
const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";

export default function PublishClient({projectId}:{projectId:string}) {
  const [details,setDetails]=useState<Details>(); const [slug,setSlug]=useState(""); const [originalSlug,setOriginalSlug]=useState("");
  const [availability,setAvailability]=useState<Availability>("not-checked"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const initialized=useRef(false);
  const load=useCallback(async()=>{try{const body=await readApiResponse<Details>(await fetch(`/api/projects/${encodeURIComponent(projectId)}/publish`));if(body){setDetails(body);if(!initialized.current){const next=body.project.slug??"";setSlug(next);setOriginalSlug(next);initialized.current=true}}}catch(reason){setMessage(reason instanceof Error?reason.message:"Unable to load publishing details.")}},[projectId]);
  useEffect(()=>{void load()},[load]);
  const normalized=slug.trim(); const validation=slugSchema.safeParse(normalized); const changed=normalized!==originalSlug;
  useEffect(()=>{if(!validation.success){setAvailability("invalid");return}setAvailability("checking");const controller=new AbortController();const timer=window.setTimeout(async()=>{try{const body=await readApiResponse<{available:boolean}>(await fetch(`/api/projects/${encodeURIComponent(projectId)}/publish/availability?slug=${encodeURIComponent(normalized)}`,{signal:controller.signal}));setAvailability(body?.available?"available":"used")}catch(reason){if(!controller.signal.aborted)setAvailability("unable")}},350);return()=>{window.clearTimeout(timer);controller.abort()}},[normalized,projectId,validation.success]);
  const publicUrl=useMemo(()=>typeof window==="undefined"?`/${normalized}`:`${window.location.origin}/${normalized}`,[normalized]);
  if(!details)return <main className={styles.shell}><p role="status">{message||"Loading publishing details…"}</p></main>;
  const project=details.project; const hasChanges=project.publishedRevision!==project.draftRevision;
  const status=!project.publishedAt?"Never published":!project.isPublished?"Unpublished":hasChanges?"Published with unpublished draft changes":"Published";
  const action=!project.publishedAt?"Publish website":hasChanges?"Republish changes":changed?"Update publishing details":"Published";
  const canSubmit=validation.success&&availability==="available"&&!busy&&(hasChanges||changed||!project.isPublished);
  const mutate=async()=>{if(!canSubmit)return;if(project.isPublished&&changed&&!window.confirm(`Change the public URL?\n\nOld: ${window.location.origin}/${originalSlug}\nNew: ${publicUrl}\n\nExisting links to the old URL will stop working.`))return;setBusy(true);setMessage("");try{await readApiResponse(await fetch(`/api/projects/${encodeURIComponent(projectId)}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slug:normalized,expectedRevision:project.draftRevision})}));setMessage("Publishing details saved.");await load();setOriginalSlug(normalized)}catch(reason){setMessage(reason instanceof ApiResponseError?reason.message:"Unable to publish. Please try again.")}finally{setBusy(false)}};
  const unpublish=async()=>{if(!window.confirm(`Unpublish “${project.name}”? The public URL will stop working.`))return;setBusy(true);try{await readApiResponse(await fetch(`/api/projects/${encodeURIComponent(projectId)}/publish`,{method:"DELETE"}),{allowEmpty:true});setMessage("Website unpublished.");await load()}catch(reason){setMessage(reason instanceof Error?reason.message:"Unable to unpublish.")}finally{setBusy(false)}};
  const copy=async()=>{try{if(!navigator.clipboard)throw new Error();await navigator.clipboard.writeText(publicUrl);setMessage("Public URL copied.")}catch{setMessage("Unable to copy the public URL. Select and copy it manually.")}};
  return <main className={styles.shell}><header><Link href="/dashboard" className={styles.back}>← Back to dashboard</Link><strong>{'{'}HTTPMAKER</strong></header><section className={styles.card}><p className={styles.eyebrow}>Publishing</p><h1>{project.name}</h1><dl><div><dt>Status</dt><dd>{status}</dd></div><div><dt>Draft updated</dt><dd>{formatDate(project.updatedAt)}</dd></div>{project.publishedAt&&<div><dt>Last published</dt><dd>{formatDate(project.publishedAt)}</dd></div>}</dl><p>Publishing creates a snapshot. Later editor changes do not change the live site until you select Republish.</p><label htmlFor="slug">Public URL slug</label><input id="slug" value={slug} onChange={event=>setSlug(event.target.value)} minLength={SLUG_MIN_LENGTH} maxLength={SLUG_MAX_LENGTH} aria-describedby="slug-help slug-status" autoComplete="off"/><small id="slug-help">{SLUG_MIN_LENGTH}–{SLUG_MAX_LENGTH} lowercase letters or numbers, separated by single hyphens. No leading, trailing, or consecutive hyphens.</small><output className={styles.url}>{publicUrl}</output><p id="slug-status" role="status">{({"not-checked":"Not checked",checking:"Checking…",available:"Available",used:"Already used",invalid:validation.success?"Invalid":validation.error.issues[0]?.message??"Invalid",unable:"Unable to check"} as Record<Availability,string>)[availability]}</p><div className={styles.preflight}><h2>Preflight</h2><p>{details.preflight.draftValid?"✓ Database draft is valid":"✕ Database draft is invalid"}</p><p>{details.preflight.unresolvedAssetCount===0?"✓ No unresolved local assets":`✕ ${details.preflight.unresolvedAssetCount} unresolved local asset(s) block publishing`}</p></div>{message&&<p role="alert" className={styles.message}>{message}</p>}<div className={styles.actions}><button onClick={()=>void mutate()} disabled={!canSubmit}>{busy?"Working…":action}</button>{project.isPublished&&project.slug&&<><a href={`/${project.slug}`} target="_blank" rel="noreferrer">View live website</a><button type="button" onClick={()=>void copy()}>Copy public URL</button><button type="button" className={styles.danger} disabled={busy} onClick={()=>void unpublish()}>Unpublish website</button></>}</div></section></main>;
}
