import { test,expect,type BrowserContext } from "@playwright/test";
import { randomBytes,randomUUID } from "node:crypto";
import { Prisma,PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { initialWebsite } from "@/data/initialWebsite";

const run=randomUUID();const ids={a:`security-a-${run}`,b:`security-b-${run}`,projectA:`security-project-a-${run}`,projectB:`security-project-b-${run}`,live:`security-live-${run}`,unpublished:`security-hidden-${run}`};
const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required for browser security tests.");const prisma=new PrismaClient({adapter:new PrismaPg({connectionString})});
const tokens={a:randomBytes(32).toString("base64url"),aOther:randomBytes(32).toString("base64url"),b:randomBytes(32).toString("base64url"),expired:randomBytes(32).toString("base64url")};
const json=JSON.parse(JSON.stringify(initialWebsite)) as Prisma.InputJsonValue;
async function cookie(context:BrowserContext,token:string){await context.addCookies([{name:"authjs.session-token",value:token,url:"http://127.0.0.1:3100",httpOnly:true,sameSite:"Lax"}])}
test.beforeAll(async()=>{const expires=new Date(Date.now()+3_600_000);await prisma.user.create({data:{id:ids.a,email:`a-${run}@example.test`,name:"Security User A",projects:{create:[{id:ids.projectA,name:"A private project",website:json,slug:`a-${run.slice(0,8)}`,editorSetupCompletedAt:new Date()},{id:ids.live,name:"A public project",website:json,slug:`live-${run.slice(0,8)}`,editorSetupCompletedAt:new Date(),isPublished:true,publishedWebsite:json,publishedAt:new Date()},{id:ids.unpublished,name:"A hidden project",website:json,slug:`hidden-${run.slice(0,8)}`,editorSetupCompletedAt:new Date()}]},sessions:{create:[{sessionToken:tokens.a,expires},{sessionToken:tokens.aOther,expires},{sessionToken:tokens.expired,expires:new Date(Date.now()-60_000)}]}}});await prisma.user.create({data:{id:ids.b,email:`b-${run}@example.test`,name:"Security User B",projects:{create:{id:ids.projectB,name:"B secret project",website:json,slug:`b-${run.slice(0,8)}`,editorSetupCompletedAt:new Date()}},sessions:{create:{sessionToken:tokens.b,expires}}}})});
test.afterAll(async()=>{await prisma.user.deleteMany({where:{id:{in:[ids.a,ids.b]}}});await prisma.$disconnect()});
test("anonymous private links redirect before data renders",async({browser})=>{for(const path of ["/dashboard",`/editor?projectId=${ids.projectA}`,`/dashboard/projects/${ids.projectA}/publish`,`/preview/${ids.projectA}`]){const context=await browser.newContext();const page=await context.newPage();await page.goto(path);await expect(page).toHaveURL(/\/login/);await expect(page.locator("body")).not.toContainText("A private project");await context.close()}});
test("user A sees only A dashboard and B object links show 404 without data",async({browser})=>{const context=await browser.newContext();await cookie(context,tokens.a);const page=await context.newPage();await page.goto("/dashboard");await expect(page.getByText("A private project")).toBeVisible();await expect(page.locator("body")).not.toContainText("B secret project");await page.goto(`/preview/${ids.projectB}`);await expect(page.locator("body")).toContainText("This page could not be found");await expect(page.locator("body")).not.toContainText("B secret project");await page.goto(`/dashboard/projects/${ids.projectB}/publish`);await expect(page.locator("body")).toContainText("This page could not be found");await expect(page.locator("body")).not.toContainText("B secret project");await context.close()});
test("expired and deleted database sessions cannot be reused",async({browser})=>{const expired=await browser.newContext();await cookie(expired,tokens.expired);let page=await expired.newPage();await page.goto("/dashboard");await expect(page).toHaveURL(/\/login/);await expired.close();const deleted=await browser.newContext();const token=randomBytes(32).toString("base64url");await prisma.session.create({data:{sessionToken:token,userId:ids.a,expires:new Date(Date.now()+3_600_000)}});await cookie(deleted,token);page=await deleted.newPage();await page.goto("/dashboard");await expect(page).toHaveURL(/\/dashboard/);await prisma.session.delete({where:{sessionToken:token}});await page.goto("/dashboard");await expect(page).toHaveURL(/\/login/);await deleted.close()});
test("revoking another session invalidates only that context",async({browser})=>{const current=await browser.newContext();const other=await browser.newContext();await cookie(current,tokens.a);await cookie(other,tokens.aOther);const page=await current.newPage();await page.goto("/dashboard/settings/security");const list=await page.request.get("/api/sessions");const sessions=(await list.json()).sessions as Array<{id:string;current:boolean}>;const otherId=sessions.find(item=>!item.current)!.id;expect((await page.request.delete(`/api/sessions/${otherId}`,{headers:{Origin:"http://127.0.0.1:3100","Sec-Fetch-Site":"same-origin"}})).status()).toBe(204);const otherPage=await other.newPage();await otherPage.goto("/dashboard");await expect(otherPage).toHaveURL(/\/login/);await page.goto("/dashboard");await expect(page).toHaveURL(/\/dashboard/);await current.close();await other.close()});
test("revoke all others preserves only the current session",async({browser})=>{const extra=randomBytes(32).toString("base64url");await prisma.session.create({data:{sessionToken:extra,userId:ids.a,expires:new Date(Date.now()+3_600_000)}});const current=await browser.newContext();const other=await browser.newContext();await cookie(current,tokens.a);await cookie(other,extra);const page=await current.newPage();await page.goto("/dashboard/settings/security");const response=await page.request.post("/api/sessions/revoke-others",{headers:{Origin:"http://127.0.0.1:3100","Sec-Fetch-Site":"same-origin"}});expect(response.status()).toBe(200);expect(await prisma.session.count({where:{userId:ids.a,expires:{gt:new Date()}}})).toBe(1);const otherPage=await other.newPage();await otherPage.goto("/dashboard");await expect(otherPage).toHaveURL(/\/login/);await page.goto("/dashboard");await expect(page).toHaveURL(/\/dashboard/);await current.close();await other.close()});
test("sign out removes the current database session and the old cookie cannot return",async({browser})=>{const context=await browser.newContext();await cookie(context,tokens.a);const page=await context.newPage();await page.goto("/dashboard");await page.locator("button[aria-expanded]").click();await page.getByRole("button",{name:"Sign out",exact:true}).click();await expect(page).toHaveURL(/\/login/);expect(await prisma.session.findUnique({where:{sessionToken:tokens.a}})).toBeNull();await cookie(context,tokens.a);await page.goto("/dashboard");await expect(page).toHaveURL(/\/login/);await context.close()});
test("public snapshots remain public and unknown/unpublished slugs are 404",async({page})=>{let response=await page.goto(`/live-${run.slice(0,8)}`);expect(response?.status()).toBe(200);await expect(page.locator("body")).toContainText("Design with a quiet confidence");response=await page.goto(`/hidden-${run.slice(0,8)}`);expect(response?.status()).toBe(404);response=await page.goto("/definitely-unknown-security-site");expect(response?.status()).toBe(404)});
test("hostile callback URLs stay on the application origin",async({page})=>{await page.goto("/login?callbackUrl=https%3A%2F%2Fevil.example");await expect(page).toHaveURL(/^http:\/\/127\.0\.0\.1:3100\/login/)});
